version: '3.7'
services:
  frontend:
    container_name: stellapac-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    image: nguyenhoamy1602/stellapac
    ports:
      - 80:80
      - 443:443
    restart: always
